### ISSUE TITLE
BIOS

### ISSUE THREAD

**Issue by orklann** [levskaya/jslinux-deobfuscated#13]
``` javascript
    loadbinary("vmlinux-2.6.20.bin", 0);
    loadbinary("root.bin", 1);
    loadbinary("linuxstart.bin", 2);
```

Which one is bios?
Which one is vgabios?
Which one is linux os?

**Comment by FreddyFeuerstein** [comment]
vmlinux-2.6.20 is the kernel,
linuxstart is the initial ram disk,
root is the rootfs.
none of them is the bios.
