### ISSUE TITLE
Network support

### ISSUE THREAD

**Issue by gdm85** [levskaya/jslinux-deobfuscated#14]
Hi there,

I have been looking through the code to try to understand what it would take to add network support. Am I correct to think that one would need to port a simple network module (and the necessary low-level network card functions) for this to work?

Any pointers appreciated :blush:

**Comment by socketpair** [comment]
jor1k.com - everything is already implemented

**Comment by gdm85** [comment]
@socketpair Oh wow, that's cool! I had skipped checking that project because I thought that RISC architecture was not interesting, well it is!
